config:
  replacements:
    - registry: quay.io
      repo_mappings:
        opendatahub/opendatahub-operator-bundle: opendatahub/opendatahub-operator-bundle
        opendatahub/opendatahub-operator: opendatahub/opendatahub-operator
        opendatahub/odh-ml-pipelines-launcher-rhel9: opendatahub/odh-ml-pipelines-launcher-rhel9
        opendatahub/odh-ml-pipelines-driver-rhel9: opendatahub/odh-ml-pipelines-driver-rhel9
        opendatahub/odh-kuberay-operator-controller-rhel9: opendatahub/odh-kuberay-operator-controller-rhel9
        opendatahub/odh-kf-notebook-controller-rhel9: opendatahub/odh-kf-notebook-controller-rhel9
        opendatahub/odh-data-science-pipelines-operator-controller-rhel9: opendatahub/odh-data-science-pipelines-operator-controller-rhel9
        opendatahub/odh-model-controller-rhel9: opendatahub/odh-model-controller-rhel9
        opendatahub/odh-trustyai-service-operator-rhel9: opendatahub/odh-trustyai-service-operator-rhel9
        opendatahub/odh-training-operator-rhel9: opendatahub/odh-training-operator-rhel9
        opendatahub/odh-dashboard-rhel9: opendatahub/odh-dashboard-rhel9
        opendatahub/odh-data-science-pipelines-argo-workflowcontroller-rhel9: opendatahub/odh-data-science-pipelines-argo-workflowcontroller-rhel9
        opendatahub/odh-ml-pipelines-persistenceagent-v2-rhel9: opendatahub/odh-ml-pipelines-persistenceagent-v2-rhel9
        opendatahub/odh-data-science-pipelines-argo-argoexec-rhel9: opendatahub/odh-data-science-pipelines-argo-argoexec-rhel9
        opendatahub/odh-ml-pipelines-scheduledworkflow-v2-rhel9: opendatahub/odh-ml-pipelines-scheduledworkflow-v2-rhel9
        opendatahub/odh-notebook-controller-rhel9: opendatahub/odh-notebook-controller-rhel9
        opendatahub/odh-mlmd-grpc-server-rhel9: opendatahub/odh-mlmd-grpc-server-rhel9
        opendatahub/odh-ml-pipelines-api-server-v2-rhel9: opendatahub/odh-ml-pipelines-api-server-v2-rhel9
        opendatahub/odh-trustyai-service-rhel9: opendatahub/odh-trustyai-service-rhel9
        opendatahub/odh-model-registry-operator-rhel9: opendatahub/odh-model-registry-operator-rhel9
        opendatahub/odh-model-registry-rhel9: opendatahub/odh-model-registry-rhel9
        opendatahub/odh-feast-operator-rhel9: opendatahub/odh-feast-operator-rhel9
        opendatahub/odh-feature-server-rhel9: opendatahub/odh-feature-server-rhel9
        opendatahub/odh-llama-stack-k8s-operator-rhel9: opendatahub/odh-llama-stack-k8s-operator-rhel9
        opendatahub/odh-llm-d-inference-scheduler-rhel9: opendatahub/odh-llm-d-inference-scheduler-rhel9
        opendatahub/odh-llm-d-routing-sidecar-rhel9: opendatahub/odh-llm-d-routing-sidecar-rhel9
        opendatahub/odh-must-gather-rhel9: opendatahub/odh-must-gather-rhel9
        opendatahub/odh-kserve-agent-rhel9: opendatahub/odh-kserve-agent-rhel9
        opendatahub/odh-kserve-controller-rhel9: opendatahub/odh-kserve-controller-rhel9
        opendatahub/odh-kserve-router-rhel9: opendatahub/odh-kserve-router-rhel9
        opendatahub/odh-kserve-storage-initializer-rhel9: opendatahub/odh-kserve-storage-initializer-rhel9
        opendatahub/odh-ta-lmes-driver-rhel9: opendatahub/odh-ta-lmes-driver-rhel9
        opendatahub/odh-ta-lmes-job-rhel9: opendatahub/odh-ta-lmes-job-rhel9
        opendatahub/odh-fms-guardrails-orchestrator-rhel9: opendatahub/odh-fms-guardrails-orchestrator-rhel9
        opendatahub/odh-trustyai-vllm-orchestrator-gateway-rhel9: opendatahub/odh-trustyai-vllm-orchestrator-gateway-rhel9
        opendatahub/odh-built-in-detector-rhel9: opendatahub/odh-built-in-detector-rhel9
        opendatahub/odh-pipeline-runtime-datascience-cpu-py312-rhel9: opendatahub/odh-pipeline-runtime-datascience-cpu-py312-rhel9
        opendatahub/odh-pipeline-runtime-minimal-cpu-py312-rhel9: opendatahub/odh-pipeline-runtime-minimal-cpu-py312-rhel9
        opendatahub/odh-pipeline-runtime-pytorch-cuda-py312-rhel9: opendatahub/odh-pipeline-runtime-pytorch-cuda-py312-rhel9
        opendatahub/odh-pipeline-runtime-pytorch-rocm-py312-rhel9: opendatahub/odh-pipeline-runtime-pytorch-rocm-py312-rhel9
        opendatahub/odh-pipeline-runtime-tensorflow-cuda-py312-rhel9: opendatahub/odh-pipeline-runtime-tensorflow-cuda-py312-rhel9
        opendatahub/odh-pipeline-runtime-tensorflow-rocm-py312-rhel9: opendatahub/odh-pipeline-runtime-tensorflow-rocm-py312-rhel9
        opendatahub/odh-workbench-codeserver-datascience-cpu-py312-rhel9: opendatahub/odh-workbench-codeserver-datascience-cpu-py312-rhel9
        opendatahub/odh-workbench-jupyter-datascience-cpu-py312-rhel9: opendatahub/odh-workbench-jupyter-datascience-cpu-py312-rhel9
        opendatahub/odh-workbench-jupyter-minimal-cpu-py312-rhel9: opendatahub/odh-workbench-jupyter-minimal-cpu-py312-rhel9
        opendatahub/odh-workbench-jupyter-minimal-cuda-py312-rhel9: opendatahub/odh-workbench-jupyter-minimal-cuda-py312-rhel9
        opendatahub/odh-workbench-jupyter-minimal-rocm-py312-rhel9: opendatahub/odh-workbench-jupyter-minimal-rocm-py312-rhel9
        opendatahub/odh-workbench-jupyter-pytorch-cuda-py312-rhel9: opendatahub/odh-workbench-jupyter-pytorch-cuda-py312-rhel9
        opendatahub/odh-workbench-jupyter-pytorch-rocm-py312-rhel9: opendatahub/odh-workbench-jupyter-pytorch-rocm-py312-rhel9
        opendatahub/odh-workbench-jupyter-tensorflow-cuda-py312-rhel9: opendatahub/odh-workbench-jupyter-tensorflow-cuda-py312-rhel9
        opendatahub/odh-workbench-jupyter-tensorflow-rocm-py312-rhel9: opendatahub/odh-workbench-jupyter-tensorflow-rocm-py312-rhel9
        opendatahub/odh-workbench-jupyter-trustyai-cpu-py312-rhel9: opendatahub/odh-workbench-jupyter-trustyai-cpu-py312-rhel9
        opendatahub/odh-guardrails-detector-huggingface-runtime-rhel9: opendatahub/odh-guardrails-detector-huggingface-runtime-rhel9
        opendatahub/odh-openvino-model-server-rhel9: opendatahub/odh-openvino-model-server-rhel9
        opendatahub/odh-vllm-cpu-rhel9: opendatahub/odh-vllm-cpu-rhel9
        opendatahub/odh-vllm-gaudi-rhel9: opendatahub/odh-vllm-gaudi-rhel9
        opendatahub/odh-model-registry-job-async-upload-rhel9: opendatahub/odh-model-registry-job-async-upload-rhel9
        opendatahub/odh-llama-stack-core-rhel9: opendatahub/odh-llama-stack-core-rhel9
        opendatahub/odh-mod-arch-model-registry-rhel9: opendatahub/odh-mod-arch-model-registry-rhel9
        opendatahub/odh-workbench-jupyter-pytorch-llmcompressor-cuda-py312-rhel9: opendatahub/odh-workbench-jupyter-pytorch-llmcompressor-cuda-py312-rhel9
        opendatahub/odh-pipeline-runtime-pytorch-llmcompressor-cuda-py312-rhel9: opendatahub/odh-pipeline-runtime-pytorch-llmcompressor-cuda-py312-rhel9
        opendatahub/odh-model-metadata-collection-rhel9: opendatahub/odh-model-metadata-collection-rhel9
        opendatahub/odh-mod-arch-gen-ai-rhel9: opendatahub/odh-mod-arch-gen-ai-rhel9
        opendatahub/odh-kube-auth-proxy-rhel9: opendatahub/odh-kube-auth-proxy-rhel9
        opendatahub/odh-model-performance-data-rhel9: opendatahub/odh-model-performance-data-rhel9
        opendatahub/odh-maas-api-rhel9: opendatahub/odh-maas-api-rhel9
        opendatahub/odh-trustyai-ragas-lls-provider-dsp-rhel9: opendatahub/odh-trustyai-ragas-lls-provider-dsp-rhel9
        opendatahub/odh-training-cuda121-torch24-py311-rhel9: opendatahub/odh-training-cuda121-torch24-py311-rhel9
        opendatahub/odh-training-cuda124-torch25-py311-rhel9: opendatahub/odh-training-cuda124-torch25-py311-rhel9
        opendatahub/odh-training-cuda128-torch28-py312-rhel9: opendatahub/odh-training-cuda128-torch28-py312-rhel9
        opendatahub/odh-training-rocm62-torch24-py311-rhel9: opendatahub/odh-training-rocm62-torch24-py311-rhel9
        opendatahub/odh-training-rocm62-torch25-py311-rhel9: opendatahub/odh-training-rocm62-torch25-py311-rhel9
        opendatahub/odh-training-rocm64-torch28-py312-rhel9: opendatahub/odh-training-rocm64-torch28-py312-rhel9
  supported-ocp-versions:
    build:
      - name: v4.20
        base-image: brew.registry.redhat.io/rh-osbs/openshift-ose-operator-registry-rhel9:v4.20
    release:
      - v4.20
