name: Insta Merge FBC Nudges

on:
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - reopened
      - edited
    paths:
      - catalog/catalog-patch.yaml
      - schedule/catalog-github-trigger.txt
  workflow_dispatch:

env:
  GITHUB_ORG: opendatahub-io
  GITHUB_REPO: ODH-Build-Config
  RESOLVE_CONFLICTS_FOR: 'catalog/catalog-patch.yaml,schedule/catalog-github-trigger.txt'


permissions:
  contents: write
  pull-requests: write
  checks: write
  security-events: write
  statuses: write

jobs:
  insta-merge:
    if: ${{ github.event.sender.login == 'red-hat-konflux'  && contains(github.event.pull_request.title, 'update odh-operator-bundle-')}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          echo $ALL_CHANGED_FILES
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

      - name: Merge Feasibility Check
        if: ${{ steps.changed-files.outputs.all_changed_files == 'catalog/catalog-patch.yaml' || steps.changed-files.outputs.all_changed_files == 'schedule/catalog-github-trigger.txt' }}
        id: merge-feasibility-check
        run: |
          # Declare variables
          BASE_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          HEAD_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          VERSION=v${BASE_BRANCH/rhoai-/}
          SUFFIX=${VERSION/./-}
          echo "SUFFIX=$SUFFIX"
          echo "HEAD_BRANCH=$HEAD_BRANCH"
          TITLE="${{ github.event.pull_request.title }}"
          
          if [[ $TITLE == chore\(deps\)* ]]
          then 
            TITLE=${TITLE/chore\(deps\): u/U}
          fi
          REGEX="^Update.*-$SUFFIX to [0-9a-z]{1,40}$"

          FEASIBLE=No
          #Check if PR title is as per the convention
          if [[ "$TITLE" =~ $REGEX ]]
          then
            FEASIBLE=Yes
            echo "It's a valid PR to merge!"
          else
            echo "Insta-merge not configured to merge this PR, skipping."
          fi
          echo "FEASIBLE=$FEASIBLE" >> $GITHUB_OUTPUT
          echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_OUTPUT
          echo "HEAD_BRANCH=$HEAD_BRANCH" >> $GITHUB_OUTPUT

      - name: Generate github-app token
        id: app-token
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.ODH_DEVOPS_APP_ID }}
          private_key: ${{ secrets.ODH_DEVOPS_APP_PRIVATE_KEY }}

      - uses: Wandalen/wretry.action@v3.5.0
        if: ${{ steps.merge-feasibility-check.outputs.FEASIBLE == 'Yes' }}
        with:
          action: red-hat-data-services/insta-merge@main
          retry_condition: steps._this.outputs.code == 0
          attempt_limit: 5
          github_token: ${{ steps.app-token.outputs.token }}
          with: |
            upstream_repo: "https://github.com/${GITHUB_ORG}/${GITHUB_REPO}.git"
            upstream_branch: "${{ steps.merge-feasibility-check.outputs.BASE_BRANCH }}"
            downstream_repo: "https://github.com/${GITHUB_ORG}/${GITHUB_REPO}.git"
            downstream_branch: "${{ steps.merge-feasibility-check.outputs.HEAD_BRANCH }}"
            token: ${{ steps.app-token.outputs.token }}
            resolve_conflicts_for: "${RESOLVE_CONFLICTS_FOR}"
            merge_args: "--no-edit"
            pr_url: "${{ github.event.pull_request.html_url }}"

