name: Insta Merge Version Sync

on:
  pull_request_target:
    branches:
      - 'main'
    types:
      - opened
      - reopened
      - edited
    paths:
      - bundle/bundle-patch.yaml
      - catalog/catalog-patch.yaml

permissions:
  contents: write
  pull-requests: write

jobs:
  version-sync-merge:
    if: ${{ github.event.pull_request.user.login == 'odh-devops-app[bot]' && contains(github.event.pull_request.title, 'sync rhoai version to') }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate github-app token
        id: app-token
        uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc # v3.0.0
        with:
          app_id: ${{ secrets.ODH_DEVOPS_APP_ID }}
          private_key: ${{ secrets.ODH_DEVOPS_APP_PRIVATE_KEY }}

      - name: Approve and merge version sync PR
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr review "$PR_URL" --approve
          gh pr merge "$PR_URL" --auto --squash
